default: &default
  adapter: postgresql
  encoding: utf8
  host: 127.0.0.1
  pool: 5
  timeout: 5000
  username: bozzhik
  password: 121212

development:
  <<: *default
  database: inkz_dev

test:
  <<: *default
  database: inkz_test

production:
  <<: *default
  database: inkz
